spring:
  application:
    name: ProductService

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductApplication
    username: postgres
    password: Kanybek12345
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
