spring:
  application:
    name: ProductApplication

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/InventoryApplication
    username: postgres
    password: Kanybek12345
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    exchange:
      name: inventory-exchange

    queue:
      name: inventory-queue

    routing:
      key: inventory-routing-key

  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

server:
  port: 8082
