spring:
  application:
    name: InventoryService

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/InventoryApplication
    username: postgres
    password: Kanybek12345
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    exchange:
      name: inventory-exchange

    queue:
      name: inventory-queue

    routing:
      key: inventory-routing-key

  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30

server:
  port: 8082
